#!/bin/bash
#SBATCH -A  Nano                # account name
#SBATCH -p  low                   # partition name
#SBATCH --time 24:00:00           # format: HH:MM:SS
#SBATCH -N 1                      # 1 node
#SBATCH --ntasks-per-node=52      # 52 tasks out of 52
#SBATCH --mem=400g                # memory per node out of 495 Gb cnode or 1000 fnode
#SBATCH --job-name=test_sisso-cpu


SISSODIR=/unimore_home/pdugoni/sissopp/bin

${SISSODIR}/sisso++ < lndiff.json 
